@startuml

title LogicalDomain.delete(absolute_index)

participant Actor as app #white
box "LogicalDomain" #white
    participant LogicalDomainService as LS
    participant CursorState as CS
    participant TextBuffer as TB
end box

app -> LS : ""delete()""
activate LS

    LS -> CS : ""get_cursor()""
    activate CS
        return ""absolute_index""

    LS -> TB : ""delete(absolute_index)""
    deactivate LS

@enduml