@startuml

title LogicalDomain.get_logical_cursor()

participant Actor as app #white
box "LogicalDomain" #white
    participant LogicalDomainService as LS
    participant CursorState as CS
    participant TextBuffer as TB
end box

app -> LS : ""get_logical_cursor()""
activate LS
    LS -> CS : ""get_cursor()""
    activate CS
        return ""abs_index""
    LS -> TB : ""get_text()""
    activate TB
        return ""text""
    LS -> LS : ""to_logical(abs_index, text)""
    activate LS
        return ""logical_position""
    return ""logical_position""

@enduml