@startuml

title LogicalDomain.get_absolute_index()

participant Actor as app #white
box "LogicalDomain" #white
    participant LogicalDomainService as LS
    participant CursorState as CS
    participant TextBuffer as TB
end box

app -> LS : ""get_absolute_index()""
activate LS
    LS -> CS : ""get_cursor()""
    activate CS
        return ""abs_index""
    return ""abs_index""

@enduml