@startuml

title DisplayDomain.backspace()

participant Actor as app #white
box "DisplayDomain" #white
    participant DomainDomainService as DS
    participant ViewportState as VS
end box
participant VisualDomain as VD #green

app -> DS : ""backspace()""
activate DS
    DS -> VD : ""backspace()""
    DS -> VD : ""get_cursor()""
    activate VD
        return ""visual_position""
    DS -> VS : ""update(visual_position)""
    deactivate DS


@enduml