@startuml

title VisualDomain.get_cursor()

participant Actor as app #white
box "VisualDomain" #white
    participant VisualDomainService as VS
    participant MovementResolver as MR
    participant VisualLogicalAdapter as VA
end box
participant LogicalDomain as LD #lightblue

app -> VS : ""get_cursor()""
activate VS
    VS -> VA : ""get_cursor()""
    activate VA
        VA -> LD : ""get_cursor()""
        activate LD
            return ""abs_index""
        VA -> VA : ""translate(abs_index)""
        activate VA
            return ""visual_position""
        return ""visual_position""
    return ""visual_position""
@enduml