@startuml

title VisualDomain.delete()

participant Actor as app #white
box "VisualDomain" #white
    participant VisualDomainService as VS
    participant MovementResolver as MR
    participant VisualLogicalAdapter as VA
end box
participant LogicalDomain as LD #lightblue

app -> VS : ""delete()""
activate VS
    VS -> VA : ""delete()""
    deactivate VS

activate VA
    VA -> LD : ""delete()""
    VA -> LD : ""get_text()""
    activate LD
        return ""text""

    VA -> VA : ""update_map()""
    deactivate VA

@enduml