@startuml

title LogicalDomain.insert(text)

participant Actor as app #white
box "LogicalDomain" #white
    participant LogicalDomainService as LS
    participant CursorState as CS
    participant TextBuffer as TB
end box

app -> LS : ""insert(text)""
activate LS
    LS -> CS : ""get_cursor()""
    activate CS
        return ""abs_index""
    LS -> TB : ""insert(text, abs_index)""

    LS -> CS : ""set_cursor(abs_index + text.length)""

    deactivate LS

@enduml