@startuml

interface AbstractTextEditor {
    ' --- Primary Display Interface ---
    +insert(text: str)
    +delete()
    +backspace()
    ..
    +get_lines() : List[VisualLineGroup]
    +get_cursor() : WindowPosition
    ..
    +move_up()
    +move_down()
    +move_left()
    +move_right()
    +move_home()
    +move_end()
    ==
    ' --- Extended Output Interfaces ---
    +raw_text() : str
    +raw_cursor() : int
    ..
    +logical_lines() : List[str]
    +logical_cursor() : LogicalPosition
    ..
    +visual_lines() : List[VisualLineGroup]
    +visual_cursor() : VisualPosition
}

class TextEditor {
    -_logical_domain : LogicalDomain
    -_visual_domain : VisualDomain
    -_display_domain : DisplayDomain
    __
    +__init__(width: int, height: int, scrolloff: int, text: str = "", cursor_index: int = None)
}

interface DisplayDomain
interface LogicalDomain
interface VisualDomain

' ----

TextEditor .up.|> AbstractTextEditor

TextEditor *-- LogicalDomain
TextEditor *-- VisualDomain
TextEditor *-- DisplayDomain

@enduml