@startuml

title Text Editor Architecture - Display Layer

interface DisplayLayer as "\nDisplayLayer"
interface VisualLayer

rectangle "Display Domain" #Orange {
   component DisplayDomainService
   ' component DisplayCoordinateTranslator
   component ViewportState
   'Stateless?
   ' component CoordinateTranslator
}

DisplayDomainService -up-|> DisplayLayer

' DisplayDomainService *--> DisplayCoordinateTranslator
DisplayDomainService *-> ViewportState
' DisplayCoordinateTranslator .> ViewportState

DisplayDomainService ..> VisualLayer

@enduml