@startuml

title Text Editor Architecture - Domain Containers  [WIP]


interface API

package TextEditor #LightGray {

interface DisplayLayer
interface VisualLayer
interface LogicalLayer

rectangle Facade #Gray
rectangle DisplayDomain #Orange
rectangle VisualDomain #Green
rectangle LogicalDomain #LightBlue
}

API - Facade
DisplayLayer - [DisplayDomain]
VisualLayer - [VisualDomain]
LogicalLayer - [LogicalDomain]

[Facade] ..> DisplayLayer : use
[DisplayDomain] ..> VisualLayer : use
[VisualDomain] ..> LogicalLayer : use

@enduml