@startuml

title Text Editor Architecture - Domain Containers


interface API

package TextEditor #LightGray {

rectangle Facade #Gray
rectangle DisplayDomain #Orange
rectangle VisualDomain #Green
rectangle LogicalDomain #LightBlue
}

Facade -up- API

Facade --> DisplayDomain
DisplayDomain -> VisualDomain
VisualDomain -> LogicalDomain
Facade --> VisualDomain
Facade --> LogicalDomain

@enduml