@startuml

title Text Editor Architecture - Domain Components  [WIP]

package  DisplayDomain {
    component Viewport
}
package  VisualDomain {
    component Cursor
    component WrapEngine
}
package  LogicalDomain{
    component TextBuffer
}

WrapEngine ..> TextBuffer
Cursor ..> TextBuffer
Cursor .> WrapEngine
Viewport ..> WrapEngine

@enduml