@startuml

title Text Editor Architecture - Logical Layer

interface LogicalLayer

rectangle "Logical Domain" #LightBlue {
   component LogicalDomainService
   component "TextBuffer"
   component "Cursor"
}

LogicalDomainService *-> TextBuffer
LogicalDomainService *--> Cursor

LogicalLayer -- LogicalDomainService

@enduml