@startuml

title Text Editor Architecture - Logical Layer

interface LogicalLayer

rectangle "Logical Domain" #LightBlue {
   component LogicalDomainService
   component "TextBuffer"
}

LogicalDomainService *-> TextBuffer

LogicalLayer -- LogicalDomainService

@enduml