@startuml

participant Host as App #white
participant "Text Editor" as Facade
participant "Display Domain" as DD #orange
participant "Visual Domain" as VD #green
participant "Logical Domain" as LD #lightblue


App -> Facade : ""delete()""
activate Facade
Facade -> DD : ""delete()""
deactivate Facade
activate DD
DD -> VD : ""delete()""
deactivate DD
activate VD
VD -> LD : ""delete()""
deactivate VD


@enduml