@startuml

title Text Editor Architecture - Visual Component

interface VisualLayer as "\nVisualLayer"
interface LogicalLayer

rectangle "Visual Domain" #Green {
   component "VisualDomainService"
   'Stateful (Orchestrator/ Facade)
   component "CursorState"
   'Stateful
   component "MovementResolver"
   'Stateful
   component "WrapEngine"
   'Stateless (Adapter Pattern?)
}

VisualDomainService -up-|> VisualLayer
WrapEngine ..> LogicalLayer : " adapts"

VisualDomainService *-> CursorState
VisualDomainService *--> WrapEngine
VisualDomainService *--> MovementResolver
WrapEngine <. CursorState

@enduml